spring:
  application:
    name: csv-stats-player-persistence
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:csv-stats-player-persistence}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      max-poll-records: ${KAFKA_MAX_POLL_RECORDS:500}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
    listener:
      type: batch
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
      specific.avro.reader: true
app:
  kafka:
    topics:
      parsed-stats-player: ${KAFKA_PARSED_STATS_PLAYER_TOPIC:stats-player.parsed}
      dlt: ${KAFKA_PLAYER_PERSISTENCE_DLT_TOPIC:stats-player.parsed.DLT}
    error:
      max-attempts: ${KAFKA_RETRY_MAX_ATTEMPTS:3}
      backoff-ms: ${KAFKA_RETRY_BACKOFF_MS:1000}
